### Add User
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullName": "Anuj Sharma",
    "phoneNumber": "7726062540",
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}
### Login User
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "bhavitkanthalia16@gmail.com",
    "password": "password"
}

### Get all Task

GET http://localhost:5000/api/todo 


###
### Get all Task by id

GET http://localhost:5000/api/todo/anujsharma11098@gmail.com


### Task registered

POST http://localhost:5000/api/todo
Content-Type: application/json

{
    "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZWRiMjM0OGU5NjYzMzFiMTA3ZmUwZWFcIixcImZ1bGxOYW1lXCI6XCJBbnVqIFNoYXJtYVwiLFwicGhvbmVOdW1iZXJcIjo3NzI2MDYyNTQwLFwiZW1haWxcIjpcImFudWpzaGFybWExMTA5OEBnbWFpbC5jb21cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkVzZYdW85cTJNeDR4ZjNscUsuY0FlZVZFVFhWWGVQZ1lXbS5rY3JMNVl2VFhhZXJhdjZpZi5cIixcImNyZWF0ZWRBdFwiOlwiMjAyMC0wNi0wNlQwNTowMjowMC40MTBaXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMjAtMDYtMDZUMDU6MDI6MDAuNDEwWlwiLFwiX192XCI6MH0iLCJpYXQiOjE1OTE0MTk5NzJ9.1L9fI7RpnFr1Q6_kNRw-ne59FGNTtThhkwDhXUch07s",
    "task" : "Project",
    "description":"Complete the work before deadline",
    "dueDate" : "2020-06-20",
    "status":"0",
    "taskType":"Work"
}